import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// REVIEW: geistMono font is loaded but never visibly used in the app — unnecessary network request.
// Either remove it or actually apply it somewhere.
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// REVIEW: Metadata still has the default Next.js boilerplate. Update title and description
// to reflect the actual app (e.g. "SK8DALEN Bowl Warriors 2026").
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* GLOBAL HEADER */}
        <div className="w-full flex items-center justify-between px-6 py-4 border-b border-zinc-800">
          {/* REVIEW: Use next/image instead of <img> to get automatic image optimization. */}
          {/* REVIEW: The logo file "sk8dalen_COMPETITION_2026_logo.png" does not exist in /public — this will show a broken image. */}
          {/* REVIEW: Typo in alt text — "WORRIORS" should be "WARRIORS". */}
          <Link href="/" className="flex items-center gap-3">
            <img
              src="/sk8dalen_COMPETITION_2026_logo.png"
              alt="SK8DALEN BOWL WORRIORS 2026"
              className="h-10"
            />
          </Link>
        </div>

        {/* PAGE CONTENT */}
        <div>{children}</div>
      </body>
    </html>
  );
}
