import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {/* GLOBAL HEADER */}
        <div className="w-full flex items-center justify-between px-6 py-4 border-b border-zinc-800">

          <Link href="/" className="flex items-center gap-3">
            <img
              src="/sk8dalen_COMPETITION_2026_logo.png"
              alt="SK8DALEN BOWL WORRIORS 2026"
              className="h-10"
            />
          </Link>

        </div>

        {/* PAGE CONTENT */}
        <div>
          {children}
        </div>

      </body>
    </html>
  );
}